
<img src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" width="631" height="307" alt="" style="margin-top:50px">
<br><br>

<div class="carousel slide" id="carousel-765973">
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#carousel-765973">
        </li>
        <li data-slide-to="1" data-target="#carousel-765973">
        </li>
        <li data-slide-to="2" data-target="#carousel-765973">
        </li>
    </ol>
    <div class="carousel-inner">

        <div class="item active">
            <img alt="" src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" />	
        </div>

        <div class="item">
            <img alt="" src="<?= $this->baseUrl() ?>/images/story1/HomeBackground.jpg" />
        </div>
        <div class="item">
            <img alt="" src="<?= $this->baseUrl() ?>/images/story1/homeStory1.jpg" />
        </div>
    </div> <a class="left carousel-control" href="#carousel-765973" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-765973" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>
